apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsphere-block-sc
provisioner: csi.vsphere.vmware.com
parameters:
  storagePolicyName: "vsphere-csi" # Replace with your exact vCenter policy name
  csi.storage.k8s.io/fstype: ext4
volumeBindingMode: Immediate
