- name: Change DNS settings
  hosts: ntp
  become: true
  gather_facts: false

  tasks:
    - name: Configure DNS servers in Netplan
      ansible.builtin.blockinfile:
        path: /etc/netplan/99-netcfg-vmware.yaml
        block: |
          nameservers:
            addresses:
              - 10.200.50.11
              - 10.200.50.12
        insertafter: "addresses:"
        mode: '0600'

    - name: Apply Netplan configuration
      ansible.builtin.command: netplan apply
