- name: Update all hosts & reboot
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check for updates and install
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 300
