- name: Install and configure Bind9
  hosts: nameservers
  become: true
  gather_facts: false

  tasks:
    - name: Install Bind9
      ansible.builtin.apt:
        name: bind9
        state: present

    - name: Upload named.conf.local
      ansible.builtin.copy:
        src: ../config/named.conf
        dest: /etc/bind/named.conf
        mode: '0640'
        owner: root
        group: root
        backup: true
