- name: Install and configure Unbound
  hosts: recursive_nameservers
  become: true
  gather_facts: false

  tasks:
    - name: Install unbound
      ansible.builtin.apt:
        name: unbound
        state: present

    - name: Configure unbound
      ansible.builtin.template:
        src: ../config/unbound.conf
        dest: /etc/unbound/unbound.conf
        mode: '0640'
        owner: root
        group: root
        backup: true
